### ISSUE TITLE
Guardar localización del usuario actual

### ISSUE THREAD

**Issue by uo270437** [Arquisoft/radarin_es3b#111]
Se ha añadido un botón para guardar la ubicación actual del usuario, ya que al intentar hacerlo de forma automática al iniciar la aplicación no se llegaba a ejecutar el método de guardar.

**Comment by Rcenador** [comment]
No está mal que sea así, a modo de "permiso" por parte del usuario para enviar su localización. En lugar de "Guardar localización" podríamos escoger un título para el botón más intuitivo para el usuario ("Enviar mi ubicación" o.. "Compartir mi ubicación").
