### ISSUE TITLE
Notificaciones mapa

### ISSUE THREAD

**Issue by UO246711** [Arquisoft/radarin_es3b#121]
Comenzar a mirar como enviar notificaciones al usuario al tener un usuario cerca

**Comment by Rcenador** [comment]
He probado [react-notifications-components](https://www.npmjs.com/package/react-notifications-component) para una primera prueba de notificación dentro del navegador. La librería tiene buena pinta (licencia del MIT y un montón de descargas). 

Al pulsar el botón de Guardar Localización (commit 09f5dea9e0383cce07cc5bc4473a873960336e04) podéis ver el ejemplo.

El siguiente paso sería comprobar si se pueden lanzar notificaciones teniendo el navegador minimizado.
