### ISSUE TITLE
Conectar la sesión de solid con mongoDB y el mapa

### ISSUE THREAD

**Issue by UO246711** [Arquisoft/radarin_es3b#122]
Se deberá conectar los datos obtenidos desde el pod de solid (y obtener los nombre de usuario), guardar la localización de un usuario al conectarse en base a ese usuario y enviar la lista de amigos al mapa.

**Comment by Rcenador** [comment]
En relación con este tema y lo comentado en la reunión con respecto a cómo hacer debugging de lo que se guarda en la base de datos  @uo270437, pego aquí una sugerencia que ya he probado y me parece bastante cómoda que es usar [MongoDB Compass](https://zellwk.com/blog/local-mongodb/#:~:text=To%20connect%20to%20your%20local,databases%20in%20your%20local%20MongoDB.)

Se instala, se crea una conexión con localhost y puerto 27017, y podrá visualizarse la base de datos local.
