### ISSUE TITLE
Notificaciones de nuevos amigos cercanos con la aplicación en segundo plano.

### ISSUE THREAD

**Issue by uo270437** [Arquisoft/radarin_es3b#129]
Buscar información sobre cómo mostrar notificaciones al usuario cuando no tiene la aplicación abierta de que un nuevo amigo está dentro del radio.

**Comment by Lu-UniOvi** [comment]
Llevo un par de días estudiando [esta](https://itnext.io/react-push-notifications-with-hooks-d293d36f4836) solución. Aún no fui capaz a comprender cómo echarla a funcionar del todo, pero en cuanto funcione podría mandar notificaciones push aún cuando el usuario no esté mirando la página. También funcionaría en móvil, el ejemplo de funcionamiento final está hecho desde uno.

**Comment by Lu-UniOvi** [comment]
Nuevas soluciones que estoy estudiando:
- https://www.smashingmagazine.com/2020/06/firebase-push-notifications-react/
- https://www.npmjs.com/package/web-push
- https://blog.logrocket.com/push-notifications-with-react-and-firebase/

Estas soluciones anteriores deberían de llegar a funcionar en móvil tambien.
De momento lo único que llegué a echar a funcionar fue [esta](https://www.npmjs.com/package/react-push-notification) solución que solo manda notificaciones push dentro del navegador. No puedo probar si funciona en móvil o si se podría usar para mandar notificaciones mientras que la aplicación no esté en primer plano.
