### ISSUE TITLE
Error al realizar los test

### ISSUE THREAD

**Issue by uo270437** [Arquisoft/radarin_es3b#154]
Al intentar ejecutar los test, se muestra un error al tratar de realizar la operación render y comprobar que se ejecuta correctamente

**Comment by UO246711** [comment]
En estos dos issues se habla del problema:
-https://github.com/kentcdodds/jest-cypress-react-babel-webpack/issues/20
-https://github.com/testing-library/react-testing-library/issues/472

**Comment by Rcenador** [comment]
Tests unitarios ya pasan. Ahora daban problemas los tests de integración (E2E) porque estaba ausente el archivo _**jest.config.js**_ (estaba renombrado a _**jest.config.js.old**_). El error no era nada descriptivo `Support for the experimental syntax 'jsx' isn't currently enabled` y despistaba bastante del problema real.
    
Sugerencia: en este proyecto yo no borraría archivos de configuración ya que toda la estructura nos fue proporcionada funcionando.

**Comment by UO246711** [comment]
Solución al problema con el mapa y los test. He probado y funciona.
https://github.com/mapbox/mapbox-gl-js/issues/10487
