### ISSUE TITLE
Tests de la aplicación

### ISSUE THREAD

**Issue by antsuarz** [Arquisoft/radarin_es3b#222]

**Comment by Rcenador** [comment]
No se ha podido simular que un usuario está en sesión. Por lo tanto todos los tests hacen comprobaciones de las partes de la aplicación en las que el usuario no está logueado.

Se ha probado a simular la sesión con varias librerías: solid-auth-client (legacy), @inrupt/solid-client-authn y solid-auth-fetcher

**Comment by Rcenador** [comment]
La librería _solid-auth-client_ es una librería legacy. Esto puede ser lo que está generando el problema con el siguiente error:  
`TypeError: _solidAuthClient.default.mockWebId is not a function`  

Inspeccionando el contenido de la librería, parece que ya no hay una función con tal denominación (mockWebId)
