### ISSUE TITLE
Informarse sobre docker y como manejar la aplicación

### ISSUE THREAD

**Issue by UO246711** [Arquisoft/radarin_es3b#42]

**Comment by UO246711** [comment]
Con el comando "docker-compose up --build" se construye la aplicacion con Docker pero aun no sabemos como aplicar los cambios en ella sin volver a instalarla

**Comment by uo270437** [comment]
Enlace con información y comandos sobre esto: https://despliegue.codeandcoke.com/doku.php?id=apuntes:docker

**Comment by Rcenador** [comment]
Aclaraciones sobre el uso de docker: https://blog.atulr.com/docker-local-environment/

Al final del artículo aparecen comandos básicos útiles como: 
- docker-compose start
- docker-compose stop
- docker-compose restart
- etc.

**Comment by Rcenador** [comment]
Cada vez que se introducen cambios en el código, hay que hacer build con Docker de nuevo:
https://github.com/Arquisoft/radarin_es3b/blob/master/webapp/README.md#launching-everything-at-the-same-time-docker-compose

¿Existe otra alternativa que agilice el proceso de testear pequeños cambios en el código?

**Comment by UO246711** [comment]
Solución provisional:

Crear una aplicación de prueba de react con el comando  "npx create-react-app my-app" y arrancandola con "npm start", en ella se pueden ir probando las funcionalidades que queramos implementar viendo los cambios instantaneamente. Cuando se tenga implementado en la app de prueba y funciona bien pasarlo a Radarín
