### ISSUE TITLE
Preferencias personales para desarrollo

### ISSUE THREAD

**Issue by Rcenador** [Arquisoft/radarin_es3b#44]
Issue para que cada miembro del equipo exponga sus preferencias, para iniciar el reparto de tareas de desarrollo y comenzar la fase de implementación:

1. Lógica
2. Interfaz de usuario
3. Persistencia

**Comment by uo270437** [comment]
María Suárez Hevia:
1. Lógica
2. Interfaz de usuario
3. Persistencia

**Comment by Lu-UniOvi** [comment]
Lucía Gutiérrez Búa

1. Persistencia
2. Lógica
3. Interfaz de usuario

Llegado el momento también podría encargarme del diseño y ejecución de los test.

**Comment by uo258352** [comment]
1. Lógica
2. Persistencia
3. Interfaz de usuario

**Comment by UO246711** [comment]
Enrique Vera Cueto:
   
    1. Logica
    2. Persistecia
    3. Interfaz de usuario

**Comment by Rcenador** [comment]
Rocío Cenador Martínez:

1. Persistencia
2. Lógica
3. Interfaz de usuario

**Comment by uo270497** [comment]
Diego Tomás Nosti

1. Lógica
2. Persistencia
3. Interfaz de usuario
