### ISSUE TITLE
Error de visualización de diagramas nuevos

### ISSUE THREAD

**Issue by Rcenador** [Arquisoft/radarin_es3b#50]
Diagramas nuevos en plantUML añadidos al apartado 5 no se visualizan correctamente:

![Captura de pantalla 2021-02-25 a las 22 52 56](https://user-images.githubusercontent.com/69198649/109224753-a8886480-77bc-11eb-822c-1ea8fabb5761.jpeg)

**Comment by Rcenador** [comment]
Problema resuelto gracias al [issue](https://github.com/Arquisoft/radarin_en1b/issues/53#issuecomment-784173209) abierto por el grupo [radarin_en1b](https://github.com/Arquisoft/radarin_en1b): 

Arreglado en: 76c1c0b608cd3fcaaf3b344b07f7e7b9362ff254

**Comment by UO246711** [comment]
Cerramos esto ya o falta corregir algo mas?
