### ISSUE TITLE
Registro, identificación y sesión de usuario

### ISSUE THREAD

**Issue by uo270437** [Arquisoft/radarin_es3b#54]

**Comment by Rcenador** [comment]
Información sobre la identificación de un usuario a través del WebID:
https://vincenttunru.gitlab.io/tripledoc/docs/writing-a-solid-app/1-authentication.html

Relacionado también con el issue #57

**Comment by UO246711** [comment]
Módulo para trabajar en react con solid que tiene varias funcionalidades de identificación y sesiones en solid, igual os sirve aquí

https://www.npmjs.com/package/@solid/react

**Comment by Rcenador** [comment]
Info explicada de las diferentes opciones de librerías disponibles para el manejo de sesiones y autentificación:
https://docs.inrupt.com/developer-tools/javascript/client-libraries/tutorial/authenticate/

Según esta [entrada](https://github.com/solid/solid-auth-client#alibrary-for-reading-and-writing-to-legacy-solid-pods), las nuevas aplicaciones no deberían usar la librería ['solid-auth-client'](https://github.com/solid/solid-auth-client) por temas de seguridad (la que propuse en el comentario anterior https://github.com/Arquisoft/radarin_es3b/issues/54#issuecomment-787919022). De todas formas, si es más sencillo con esa librería, podríamos dejar el tema pendiente de investigación y generar una deuda técnica que sería la de mejorar en seguridad.

**Comment by UO246711** [comment]
He encontrados dos opciones viables que podemos usar, la primera es @solid/react, que es quizá menos fino pero parece mas facil para empezar a usar solid con react hasta que aprendamos mas, aparte que tiene una guía muy buena en su repositorio:

-Repositorio: https://github.com/solid/react-components

-Tutorial: https://trav.page/log/write-solid/

El elemento popup.hmtl que no funcionaba se puede acceder a el desde: https://solid.github.io/solid-auth-client/dist/popup.html hasta que encontremos una opción mejor. Información sacada de  https://github.com/Arquisoft/viade_es1c

La otra opción es https://github.com/solid/react-components, parece bastante mas elegante y con mas opciones pero mucho mas proeblematica por lo que he visto y no he encontrado ninguna guia al respecto (aún)

**Comment by uo270437** [comment]
Página con ejemplo para ocultar y mostrar componentes, útil para formulario de login/registro y para mostrar solo las partes que queramos de la aplicación en cada momento (si no está registrado solo formulario)
https://es.stackoverflow.com/questions/267656/ocultar-o-mostrar-un-div-con-un-boton-react
