### ISSUE TITLE
Conectar la aplicación con los pods de los usuarios y leer la información de ellos (especialmente los amigos)

### ISSUE THREAD

**Issue by uo270437** [Arquisoft/radarin_es3b#57]

**Comment by Rcenador** [comment]
Dejo aquí el repositorio de una aplicación que se basa en la comunicación con los pods de SOLID. Nos puede servir de ejemplo para investigar procesos como Log In con SOLID y consultar/agregar/eliminar amigos en SOLID:

https://github.com/empathyco/solid-oh-my-pod

**Comment by Rcenador** [comment]
[LDFlex](https://github.com/solid/query-ldflex#ldflex-for-solid) posible librería candidata para obtener la información del usuario, como su lista de amigos: solid.data.user.friends.

Ejemplo de uso con NodeJS: https://github.com/solid/query-ldflex#within-nodejs-environments

**Comment by Rcenador** [comment]
> [LDFlex](https://github.com/solid/query-ldflex#ldflex-for-solid) posible librería candidata para obtener la información del usuario, como su lista de amigos: solid.data.user.friends.
> 
> Ejemplo de uso con NodeJS: https://github.com/solid/query-ldflex#within-nodejs-environments

Ejemplo probado y funcionando en local con mi webID. Susceptible de integrar en el proyecto. 

![Captura de pantalla 2021-03-01 a las 13 42 59](https://user-images.githubusercontent.com/69198649/109498696-1d48f080-7a94-11eb-8420-af67fa174965.jpeg)
