### ISSUE TITLE
Error con el app.test.js y el componente geoLocation

### ISSUE THREAD

**Issue by UO246711** [Arquisoft/radarin_es3b#68]
El test da un error al hacer un commit en master cuando esta el componente de localizacion y no se carga la web, comentando el test funciona de forma provisional pero si alguien encuentra una respuesta que comente por aqui.

**Comment by Rcenador** [comment]
La explicación de lo que hace ese test que está en App.test.js la resumen bastante bien aquí:
https://stackoverflow.com/a/60747011

Básicamente lo que hace es buscar en los elementos del DOM algún texto que haga matching con la expresión regular: 
`/learn react/i`

Al no encontrar ese texto en el DOM de nuestra app, el test falla. Entiendo que es un test que viene por defecto al crear una app de React.

La solución intuyo que sería la de sustituir esa expresión regular, por otra que concuerde con el texto que renderiza nuestra aplicación, o bien, como has hecho tú, comentar o eliminar ese test y crear los nuestros propios.

**Comment by UO246711** [comment]
He probado con algún módulo distinto y con hooks, y en todos da errores el test, con los hooks de hecho da otros errores inesperados, dejaremos el test comentado para poder trabajar hasta que averigüemos como manejar los test

**Comment by Rcenador** [comment]
He conseguido que el App.test.js pase (no falle). Efectivamente el problema venía de la librería mapbox-gl. No era capaz de encontrar ese módulo porque el path no estaba correcto. En concreto, he sutituido esta línea:  

https://github.com/Arquisoft/radarin_es3b/blob/17cbc7d152abccb9e8672a0ba6238a447cd8e77c/webapp/src/components/localizacion/Map.js#L14  

Por esta:

`mapboxgl.workerClass = require("mapbox-gl/dist/mapbox-gl-csp-worker").default;`  

He probado la aplicación y parece funcionar de manera correcta también con este cambio (el mapa se renderiza y me localiza)
